workflows:
  version: 2
  build-deploy:
    jobs:
      - build


version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: powershell
          command: |
            powershell
            dir
      - run:
          name: dotnet
          command: |
            dotnet restore
